version: '3'

services:
  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/html/
    ports:
      - "80:80"
    networks:
      - app-network
    command: nginx -g "daemon off;"
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: php
    volumes:
      - ./:/var/www/html/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  # pgsql:
  #   build: ./docker/pgsql
  #   container_name: pgsql
  #   environment:
  #     POSTGRES_DB: database
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgsql:/var/lib/postgresql/data
  #   networks:
  #     - src-network

networks:
  app-network:
    driver: bridge

volumes:
  pgsql:
    driver: 'local'
